name: Hello World

on:
  workflow_dispatch:

jobs:
  test_my_project:
    runs-on: ubuntu-latest
    steps:
      name: Check Code
      uses: actions/checkout@v2
      name: Run hello World
      runs: echo "hello world"
