name: Hello World

on:
  workflow_dispatch:

jobs:
  test_my_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run hello World
        run: echo "hello world"
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install requirements
        run: 
          python -m pip install pip --upgrade
          # python -m pip3 install -r /mysite/requirements.txt

