name: Hello World

on:
  workflow_dispatch:

jobs:
  test_my_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run hello World
        run: echo "hello world"
